#!/usr/bin/env sh

set -e

setup/echo-banner "Setting up Homebrew"

if ! which brew > /dev/null; then
  echo "Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Homebrew already installed"
fi

echo "Installing Homebrew dependencies"
brew bundle
