#!/usr/bin/env sh

setup/echo-banner "Tweaking Mac defaults"

#################
# General UI/UX #
#################

# Make Bluetooth icon visible in the menu bar
defaults write com.apple.controlcenter 'NSStatusItem Visible Bluetooth' -bool true

# Reduce motion
defaults write com.apple.universalaccess reduceMotion -bool true
defaults write com.apple.Accessibility ReduceMotionEnabled -bool true

############
# Controls #
############

# Increase mouse tracking to the fastest speed
defaults write -g com.apple.mouse.scaling 3

# Make mouse scrolling a bit faster
defaults write -g com.apple.scrollwheel.scaling 1

defaults write -g com.apple.trackpad.scaling 2

# Speed up the key repeat
defaults write -g KeyRepeat -int 2

# Speed up the initial key repeat wait
defaults write -g InitialKeyRepeat -int 10

##########
# Finder #
##########

# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

#########################
# Dock, Mission Control #
#########################

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

# Don't automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

##########
# Safari #
##########

# Enable the Develop menu in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true

####################
# Other Apple Apps #
####################

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

#############
# Finish Up #
#############

echo ""
echo "Done tweaking Mac defaults. You'll need to restart now"
